#ANN Implementation of NOR Gate
Mohammed Rushad (181CO232)

In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense

In [3]:
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
target_data = np.array([[1],[0],[0],[0]], "float32")

In [4]:
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [5]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

In [7]:
model.fit(training_data, target_data, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0390 - binary_accuracy: 1.0000
Epoch 2/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0389 - binary_accuracy: 1.0000
Epoch 3/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0389 - binary_accuracy: 1.0000
Epoch 4/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0388 - binary_accuracy: 1.0000
Epoch 5/200
1/1 [==============================] - 0s 8ms/step - loss: 0.0388 - binary_accuracy: 1.0000
Epoch 6/200
1/1 [==============================] - 0s 9ms/step - loss: 0.0387 - binary_accuracy: 1.0000
Epoch 7/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0387 - binary_accuracy: 1.0000
Epoch 8/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0386 - binary_accuracy: 1.0000
Epoch 9/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0386 - binary_accuracy: 1.0000
Epoch 10/200
1/1 [==============================] - 0s 4ms/step 

In [8]:
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

1/1 [==============================] - 0s 119ms/step - loss: 0.0298 - binary_accuracy: 1.0000

binary_accuracy: 100.00%


In [9]:
print("AND Gate ANN Predicted Values:")
print(model.predict(training_data).round())

AND Gate ANN Predicted Values:
[[1.]
 [0.]
 [0.]
 [0.]]


In [30]:
X1 = np.array([[0,0]])
X2 = np.array([[0,1]])
X3 = np.array([[1,0]])
X4 = np.array([[1,1]])
print("Truth Table\n\n  A B\t\tA NOR B")
print(X1,"\t", model.predict_classes(X1))
print(X2,"\t", model.predict_classes(X2))
print(X3,"\t", model.predict_classes(X3))
print(X4,"\t", model.predict_classes(X4))
print("\n______________________\n")

Truth Table

  A B		A NOR B
[[0 0]] 	 [[1]]
[[0 1]] 	 [[0]]
[[1 0]] 	 [[0]]
[[1 1]] 	 [[0]]

______________________



/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
